apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
<<<<<<< HEAD
=======
<<<<<<< HEAD:community-operators/apicurito/apicurito.crd.yaml
  name: apicuritos.apicur.io
spec:
  group: apicur.io
  names:
    kind: Apicurito
    listKind: ApicuritoList
    plural: apicuritos
    singular: apicurito
=======
>>>>>>> Synopsys Operator 2019.8.4 made and tested
  name: bucketclasses.noobaa.io
spec:
  group: noobaa.io
  names:
    kind: BucketClass
    listKind: BucketClassList
    plural: bucketclasses
    singular: bucketclass
<<<<<<< HEAD
=======
>>>>>>> Synopsys Operator 2019.8.4 made and tested:upstream-community-operators/noobaa/noobaa_v1alpha1_bucketclass_crd.yaml
>>>>>>> Synopsys Operator 2019.8.4 made and tested
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
